### ISSUE TITLE
Error when reindexing all products

### ISSUE THREAD

**Issue by brenjt** [algolia/algoliasearch-magento-2#190]
When I run this command ```php bin/magento indexer:reindex``` in my logs of the indexing process I get this error:

```
[2017-03-24 03:37:51] main.INFO: Queue processing  [KO]: Mage::getSingleton(Algolia\AlgoliaSearch\Helper\Data)->rebuildProductIndex({"store_id":1,"product_ids":null,"page":1,"page_size":"100","useTmpIndex":"1"}) [] []
[2017-03-24 03:37:51] main.INFO: 2017-03-24T03:37:51+00:00 ERROR: ReflectionException: 'Class  does not exist' in vendor/magento/framework/Code/Reader/ClassReader.php:19
Stack trace:
#0 vendor/magento/framework/Code/Reader/ClassReader.php(19): ReflectionClass->__construct('')
#1 vendor/magento/framework/ObjectManager/Definition/Runtime.php(44): Magento\Framework\Code\Reader\ClassReader->getConstructor('')
#2 vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(71): Magento\Framework\ObjectManager\Definition\Runtime->getParameters('')
#3 vendor/magento/framework/ObjectManager/ObjectManager.php(57): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('', Array)
#4 vendor/magento/framework/Pricing/Price/Factory.php(47): Magento\Framework\ObjectManager\ObjectManager->create('', Array)
#5 vendor/magento/framework/Pricing/Price/Collection.php(136): Magento\Framework\Pricing\Price\Factory->create(Object(Magento\Catalog\Model\Product\Interceptor), NULL, NULL)
#6 vendor/magento/framework/Pricing/PriceInfo/Base.php(61): Magento\Framework\Pricing\Price\Collection->get('regular_price')
#7 vendor/algolia/algoliasearch-magento-2/Helper/Entity/ProductHelper.php(380): Magento\Framework\Pricing\PriceInfo\Base->getPrice('regular_price')
#8 app/code/MM/Overrides/Helper/Algolia/Entity/ProductHelper.php(281): Algolia\AlgoliaSearch\Helper\Entity\ProductHelper->handlePrice(Object(Magento\Catalog\Model\Product\Interceptor), Array, Array)
#9 vendor/algolia/algoliasearch-magento-2/Helper/Data.php(466): MM\Overrides\Helper\Algolia\Entity\ProductHelper->getObject(Object(Magento\Catalog\Model\Product\Interceptor))
#10 vendor/algolia/algoliasearch-magento-2/Helper/Data.php(538): Algolia\AlgoliaSearch\Helper\Data->getProductsRecords(1, Object(Magento\Catalog\Model\ResourceModel\Product\Collection\Interceptor), NULL)
#11 vendor/algolia/algoliasearch-magento-2/Helper/Data.php(340): Algolia\AlgoliaSearch\Helper\Data->rebuildStoreProductIndexPage(1, Object(Magento\Catalog\Model\ResourceModel\Product\Collection\Interceptor), 1, '100', NULL, NULL, '1')
#12 [internal function]: Algolia\AlgoliaSearch\Helper\Data->rebuildProductIndex(1, NULL, 1, '100', '1')
#13 vendor/algolia/algoliasearch-magento-2/Model/Queue.php(128): call_user_func_array(Array, Array)
#14 vendor/algolia/algoliasearch-magento-2/Model/Queue.php(141): Algolia\AlgoliaSearch\Model\Queue->run(1)
#15 vendor/algolia/algoliasearch-magento-2/Model/Queue.php(66): Algolia\AlgoliaSearch\Model\Queue->run(1)
#16 vendor/algolia/algoliasearch-magento-2/Model/Indexer/QueueRunner.php(50): Algolia\AlgoliaSearch\Model\Queue->runCron()
#17 vendor/magento/module-indexer/Model/Indexer.php(412): Algolia\AlgoliaSearch\Model\Indexer\QueueRunner->executeFull()
#18 vendor/magento/module-indexer/Console/Command/IndexerReindexCommand.php(57): Magento\Indexer\Model\Indexer->reindexAll()
#19 vendor/symfony/console/Symfony/Component/Console/Command/Command.php(257): Magento\Indexer\Console\Command\IndexerReindexCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#20 vendor/symfony/console/Symfony/Component/Console/Application.php(874): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#21 vendor/symfony/console/Symfony/Component/Console/Application.php(195): Symfony\Component\Console\Application->doRunCommand(Object(Magento\Indexer\Console\Command\IndexerReindexCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#22 vendor/magento/framework/Console/Cli.php(96): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#23 vendor/symfony/console/Symfony/Component/Console/Application.php(126): Magento\Framework\Console\Cli->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#24 bin/magento(23): Symfony\Component\Console\Application->run()
#25 {main} [] []
```

As a result I cannot get Algolia to reindex all of my products. I am having to re-save each product for it to reindex. Thoughts?

**Comment by brenjt** [comment]
This is happening because I have a product without a price. We should probably add some handling for such cases. The product is a giftcard.

**Comment by JanPetr** [comment]
Hello @brenjt, any chance you use AheadWork gift card extension? (#230)

**Comment by JanPetr** [comment]
Hello @brenjt,
thanks for getting back to me. I just wanted to confirm that it's the same issue.
We don't have solution yet. When we have one, I'll come back to you.
I'm closing the issue now in favor of #230, you can follow the progress there.
