### ISSUE TITLE
Error Indexing: PHP Fatal error:  Uncaught Error: Call to a member function getPriceInfo() on null in vendor/magento/module-grouped-product/Pricing/Price/FinalPrice.php:34

### ISSUE THREAD

**Issue by careys7** [algolia/algoliasearch-magento-2#278]
The following error occurs when reindexing on Magento 2 EE 1.7 using grouped products:

```
PHP Fatal error:  Uncaught Error: Call to a member function getPriceInfo() on null in /app/vendor/magento/module-grouped-product/Pricing/Price/FinalPrice.php:34
Stack trace:
#0 /app/vendor/algolia/algoliasearch-magento-2/Helper/Entity/ProductHelper.php(391): Magento\GroupedProduct\Pricing\Price\FinalPrice->getValue()
#1 /app/vendor/algolia/algoliasearch-magento-2/Helper/Entity/ProductHelper.php(811): Algolia\AlgoliaSearch\Helper\Entity\ProductHelper->handlePrice(Object(Magento\Catalog\Model\Product\Interceptor), Object(Magento\Catalog\Model\ResourceModel\Product\Collection\Interceptor), Array)
#2 /app/vendor/magento/framework/Interception/Interceptor.php(74): Algolia\AlgoliaSearch\Helper\Entity\ProductHelper->getObject(Object(Magento\Catalog\Model\Product\Interceptor))
#3 /app/vendor/magento/framework/Interception/Chain/Chain.php(70): Algolia\AlgoliaSearch\Helper\Entity\ProductHelper\Interceptor->___callParent('getObject', Array)
#4 /app/vendor in /app/u7tzidejubbri/vendor/magento/module-grouped-product/Pricing/Price/FinalPrice.php on line 34
```

**Comment by JanPetr** [comment]
Hello @careys7,

I'm really sorry to hear that. Unfortunately currently I don't have access to Magento EE so I cannot investigate and fix the issue :(
Would you be able to see what's going on there and send a PR?

Thanks a lot!
