### ISSUE TITLE
Fetching an error during Indexer reindex for Algoliasearch.

### ISSUE THREAD

**Issue by amispatel** [algolia/algoliasearch-magento-2#459]
After Install Algoliasearch in Magento 2. i was not able for indexer:reindex in to magento i get error during Indexer:reindex like this

PHP Fatal error:  Uncaught Error: Call to a member function getUrl() on null in /var/www/html/../../vendor/algolia/algoliasearch-magento-2/Helper/Entity/PageHelper.php:107
Stack trace:
#0 /var/www/html/../../vendor/algolia/algoliasearch-magento-2/Helper/Data.php(207): Algolia\AlgoliaSearch\Helper\Entity\PageHelper->getPages(9)
#1 [internal function]: Algolia\AlgoliaSearch\Helper\Data->rebuildStorePageIndex(9)
#2 /var/www/html/../../vendor/algolia/algoliasearch-magento-2/Model/Queue.php(71): call_user_func_array(Array, Array)
#3 /var/www/html/../../vendor/algolia/algoliasearch-magento-2/Model/Indexer/Page.php(77): Algolia\AlgoliaSearch\Model\Queue->addToQueue('Algolia\\Algolia...', 'rebuildStorePag...', Array, 1)
#4 /var/www/html/../../vendor/magento/module-indexer/Model/Indexer.php(412): Algolia\AlgoliaSearch\Model\Indexer\Page->executeFull()
#5 /var/www/html/../../vendor/magento/module-indexer/Model/Indexer/DependencyDecorator.php( in /var/www/html/../../vendor/algolia/algoliasearch-magento-2/Helper/Entity/PageHelper.php on line 107

**Comment by amispatel** [comment]
Hello,

I use Magento ver. 2.2.2.

Thank You.

**Comment by boogsau** [comment]
Hi @JanPetr, Ami logged this on my behalf. I have upgraded to a paid Algolia plan, so I'd really like to get an answer here...

**Comment by mirkocesaro** [comment]
Hi,
I have the same problem with 2.2.3.

As I understand, this happen when one store is not activated, in the method `Algolia\AlgoliaSearch\Helper\Entity\PageHelper::getStores() `
returns only activated stores, while the method `Algolia\AlgoliaSearch\Model\Indexer\Page::executeFull() `
at row 69 uses all stores. In this way, the method  
`$this->getStoreUrl($storeId)`
returns null, it throw PHP Fatal error with getUrl() on null.

**Comment by peterjaap** [comment]
@mirkocesaro good find!

**Comment by damcou** [comment]
Hi,
Thanks a lot for your investigation @mirkocesaro , we will dig deeper into this and come back to you ASAP.

**Comment by mirkocesaro** [comment]
Hi,
is there any release planned with the fix?

**Comment by damcou** [comment]
Hi @mirkocesaro ,

Sorry for the late answer.
The fix will be part our next release (it is available in the develop branch), but unfortunately we don't have any ETA for the moment.

You can find it [here](https://github.com/algolia/algoliasearch-magento-2/commit/3268d362b45175161e9ae5f8393efbb428285a1a)

**Comment by mirkocesaro** [comment]
Thank you @damcou 
I just saw the new release 1.7.0 with the fix #475
