### ISSUE TITLE
[BUG] Facing an error during Indexer reindex for Algoliasearch | getGalleryImagesJson

### ISSUE THREAD

**Issue by fernandofauth** [algolia/algoliasearch-magento-2#472]
Magento version: 2.2.3 with sample data
Algolia Seach version: 1.6.0

**Bug: What is the current behavior?**
Error on print
http://prntscr.com/j50qk5

And here the de error description:

PHP Fatal error:  Uncaught Error: Call to a member function getMediaGalleryImages() on null in /usr/share/nginx/html/magento2/vendor/magento/module-catalog/Block/Product/View/Gallery.php:58
Stack trace:
#0 /usr/share/nginx/html/magento2/generated/code/Magento/Catalog/Block/Product/View/Gallery/Interceptor.php(24): Magento\Catalog\Block\Product\View\Gallery->getGalleryImages()
#1 /usr/share/nginx/html/magento2/vendor/magento/module-catalog/Block/Product/View/Gallery.php(114): Magento\Catalog\Block\Product\View\Gallery\Interceptor->getGalleryImages()
#2 /usr/share/nginx/html/magento2/generated/code/Magento/Catalog/Block/Product/View/Gallery/Interceptor.php(63): Magento\Catalog\Block\Product\View\Gallery->getGalleryImagesJson()
#3 /usr/share/nginx/html/magento2/app/code/WebDrasil/Widgets/view/frontend/templates/widget/product/view/gallery.phtml(64): Magento\Catalog\Block\Product\View\Gallery\Interceptor->getGalleryImagesJson()
#4 /usr/share/nginx/html/magento2/vendor/magento/framework/View/TemplateEngine/Php.php(59): include('/us in /usr/share/nginx/html/magento2/vendor/magento/module-catalog/Block/Product/View/Gallery.php on line 58
	    	    		        <div class="container   "  >
				<div >
	        	<div class="inner  container " >
			    			    			    			    <div class="row row-level-1  " >
			        			        	 									            <div  class=" col-xl-6 col-lg-6 col-md-6 col-sm-12 col-12  "   >

			            	
				            
			            	<div class="col-inner " >
			                			                	
			                					                		<div  >
			                		
			                    	<div style="width:100%">
    <div class="gallery-placeholder _block-content-loading" data-gallery-role="gallery-placeholder">
    <div data-role="loader" class="loading-mask">
        <div class="loader">
            <img src="https://homolog.icresci.com.br/pub/static/frontend/WebDrasil/theme01/pt_BR/images/loader-1.gif"
            alt="Loading...">
        </div>
    </div>
</div> 
<script type="text/x-magento-init">
    {
        "[data-gallery-role=gallery-placeholder]": {
            "mage/gallery/gallery": {
                "mixins":["magnifier/magnify"],
                "magnifierOpts": {"top":"","left":"","width":"300","height":"","eventType":"hover","enabled":"false","mode":"inside"},

**Comment by fernandofauth** [comment]
The error was a conflict with another module.
